# Generated by Django 3.0.5 on 2020-06-04 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0006_auto_20200603_2156'),
        ('accounthistory', '0003_accounthistory_transfer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounthistory',
            name='transaction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='transactions.Transaction'),
        ),
    ]
