# Generated by Django 3.0.5 on 2020-05-08 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgettracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgettracker',
            name='monthly_spend',
            field=models.FloatField(default=0),
        ),
    ]
