# Generated by Django 3.0.5 on 2020-04-30 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='descripton',
            field=models.CharField(default='some transaction', max_length=200),
        ),
    ]
