# Generated by Django 3.0.5 on 2020-05-01 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200430_2234'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accountbalance',
            old_name='account',
            new_name='account_name',
        ),
        migrations.AlterField(
            model_name='account',
            name='account_name',
            field=models.CharField(max_length=200),
        ),
    ]
