# Generated by Django 3.0.5 on 2020-06-04 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_auto_20200519_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='trans_date',
            field=models.DateTimeField(),
        ),
    ]
