# Generated by Django 3.0.5 on 2020-05-22 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_category_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='carry_over',
            field=models.BooleanField(default=False),
        ),
    ]
