# Generated by Django 3.0.5 on 2020-06-11 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0003_category_carry_over'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='savings_or_investment',
            field=models.BooleanField(default=False),
        ),
    ]
