# Generated by Django 3.0.5 on 2020-05-01 02:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_amount', models.FloatField()),
                ('transfer_date', models.DateField()),
                ('incoming_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_account', to='accounts.AccountBalance')),
                ('outgoing_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.AccountBalance')),
            ],
        ),
    ]
