# Generated by Django 3.0.5 on 2020-05-01 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20200501_0825'),
        ('transfers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfer',
            name='incoming_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_account', to='accounts.Account'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='outgoing_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Account'),
        ),
    ]
