# Generated by Django 3.0.5 on 2020-05-01 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfers', '0002_auto_20200501_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfer',
            name='transfer_date',
            field=models.DateTimeField(),
        ),
    ]
