# Generated by Django 3.0.5 on 2020-05-13 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfers', '0003_auto_20200501_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfer',
            name='transfer_date',
            field=models.DateField(),
        ),
    ]
