# Generated by Django 3.0.5 on 2020-06-04 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfers', '0005_transfer_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfer',
            name='transfer_date',
            field=models.DateTimeField(),
        ),
    ]
